api: 1.14.4-R0.1-SNAPSHOT
api-version: "1.14"
main: dev.buha007.restrictedpvp.Main
name: RestrictedPvP
version: "1.2 for 1.13.3"
author: Bufnita
commands:
  pvp:
    description: main command
    usage: /pvp <args>
